version = 1
SPDX-PackageName = "Kapsule"
SPDX-PackageSupplier = "Lasath Fernando <devel@lasath.org>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/fernie/kapsule"

[[annotations]]
path = ".github/instructions/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
